version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run: yarn run build
      - run: yarn run test
      - run: yarn run size

  storybook:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run: yarn run storybook-to-ghpages

workflows:
  version: 2
  build:
    jobs:
      - build
      - storybook:
          requires:
            - build
          filters:
            branches:
              only:
                - master
